version: '2'
services:
    nginx_negro:
        image: nginx:latest
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        depends_on:
            - php
            - mysqldb
    php:
        image: php:7-fpm
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:latest
        container_name: ${MYSQL_HOST}
        env_file:
            - "./docker/.env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_RANDOM_ROOT_PASSWORD=lalala
        ports:
            - "8990:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"