version: '2'
services:
    nginx_negro:
        image: nginx:latest
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=$${NGINX_HOST}
        depends_on:
            - php
            - mysqldb
    php:
        image: php:7-fpm
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:latest
        container_name: "mysql"
        env_file:
            - "./docker/.env"
        environment:
            - MYSQL_DATABASE=$${DATABASE}
            - MYSQL_ROOT_PASSWORD=$${ROOT_PASSWORD}
            - MYSQL_USER=$${USER}
            - MYSQL_PASSWORD=$${PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=$${ALLOW_EMPTY_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=$${RANDOM_ROOT_PASSWORD}
        ports:
            - "8990:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"