version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./application:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=$${NGINX_HOST}
        depends_on:
            - php
            - mysqldb
    php:
        image: php:7-fpm
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./application:/var/www/html"
    mysqldb:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=youpi
        ports:
            - "3306:3306"
        volumes:
            - ~/mysql:/var/lib/mysql
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - mysqldb:db
